version: "1"

services:
  db:
    image: postgres
    container_name: ba_postgres
    env_file:
      - ./server/.envs/.postgres.env
    ports:
      - "5432:5432"
  pgadmin:
    container_name: ba_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./server/.envs/.pgadmin.env
    ports:
      - "5050:80"
  server:
    build:
      context: ./server
      dockerfile: "./Dockerfile"
    container_name: ba_server
    command: npm run dev
    restart: always
    depends_on:
      - db
    env_file:
      - ./server/.envs/.app.env
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: "./Dockerfile"
    container_name: ba_client
    command: npm start
    depends_on:
      - server
      - db
    env_file:
      - ./client/.envs/.app.env
    ports:
      - "3000:3000"
    links:
      - server